apiVersion: apps/v1
kind: Deployment
metadata:
  name: edpingestionlog
spec:
  selector:
    matchLabels:
      run: edpingestionlog
  replicas: 0
  template:
    metadata:
      labels:
        run: edpingestionlog
    spec:
     containers:
     - name: mycontainer
       image: docker.repo1.uhc.com/bds_oso_id/edp_trans_ingestion_log-master
       securityContext:
         runAsUser: 31000
         allowPrivilegeEscalation: false
       ports:
       - containerPort: 8080
       imagePullPolicy: Always
       resources:
        requests:
          memory: "300Mi"
          cpu: "100m"
        limits:
          memory: "2Gi"
          cpu: "1500m"
       env:
        - name: APP_NAME
          value: "hcp-prd"
        - name: ENV_PROFILE
          value: "HCPPROD"
        - name: THREADS
          value: "5"
        - name: MAX_CON_POOL
          value: "5"
        - name: MIN_CON_POOL
          value: "0"
        - name: CON_URL
          valueFrom:
           configMapKeyRef:
              name: common-property
              key: prop.ctcpgconurl
        - name: JAVA_OPTS
          value: -Xms1G -Xmx1G
        - name: SECRETS_EDP_USER
          valueFrom:
           secretKeyRef:
              name: edp-prod-security
              key: spring.user.name
        - name: SECRETS_EDP_USER_PASSWD
          valueFrom:
           secretKeyRef:
              name: edp-prod-security
              key: spring.user.password
        - name: SECRETS_SPLUNK_TOKEN
          valueFrom:
           secretKeyRef:
              name: edp-prod-security
              key: spring.splunk.token
        - name: TRUSTSTORE_PWD
          valueFrom:
            secretKeyRef:
              name: edp-prod-kafka-pwd
              key: attunity.hcp.truststore
        - name: KEYSTORE_PWD
          valueFrom:
            secretKeyRef:
              name: edp-prod-kafka-pwd
              key: attunity.hcp.keystore
        - name: KEY_PWD
          valueFrom:
            secretKeyRef:
              name: edp-prod-kafka-pwd
              key: attunity.hcp.keystore





